#!/bin/bash

[ ! -d /config/sonarr ] && mkdir -p /config/sonarr

function handle_signal {
  PID=$!
  echo "received signal. PID is ${PID}"
  kill -s SIGHUP $PID
}

trap "handle_signal" SIGINT SIGTERM SIGHUP

echo "starting sonarr"
mono /opt/NzbDrone/NzbDrone.exe -no-browser -data=/config/sonarr & wait
echo "stopping sonarr"
